# Q1. What is Min-Max scaling, and how is it used in data preprocessing? Provide an example to illustrate its  application.

Min Max scalling is a data normalization technique as it is used 
to bring the data in the range of 0,1.This technique is mostly used in 
neural networks 

In [8]:
import seaborn as sns
import pandas as pd
import numpy as np

In [2]:
df=sns.load_dataset('taxis')

In [3]:
df.head()

pickup              dropoff  passengers  distance  fare   tip  \
0  2019-03-23 20:21:09  2019-03-23 20:27:24           1      1.60   7.0  2.15   
1  2019-03-04 16:11:55  2019-03-04 16:19:00           1      0.79   5.0  0.00   
2  2019-03-27 17:53:01  2019-03-27 18:00:25           1      1.37   7.5  2.36   
3  2019-03-10 01:23:59  2019-03-10 01:49:51           1      7.70  27.0  6.15   
4  2019-03-30 13:27:42  2019-03-30 13:37:14           3      2.16   9.0  1.10   

   tolls  total   color      payment            pickup_zone  \
0    0.0  12.95  yellow  credit card        Lenox Hill West   
1    0.0   9.30  yellow         cash  Upper West Side South   
2    0.0  14.16  yellow  credit card          Alphabet City   
3    0.0  36.95  yellow  credit card              Hudson Sq   
4    0.0  13.40  yellow  credit card           Midtown East   

            dropoff_zone pickup_borough dropoff_borough  
0    UN/Turtle Bay South      Manhattan       Manhattan  
1  Upper West Side South      Manhattan       Manhattan  
2           West Village      Manhattan       Manhattan  
3         Yorkville West      Manhattan       Manhattan  
4         Yorkville West      Manhattan       Manhattan

In [4]:
from sklearn.preprocessing import MinMaxScaler


In [6]:
min_max=MinMaxScaler()

In [7]:
min_max.fit_transform(df[['tip']])

array([[0.06475904],
       [0.        ],
       [0.07108434],
       ...,
       [0.        ],
       [0.        ],
       [0.10120482]])

# Q2. What is the Unit Vector technique in feature scaling, and how does it differ from Min-Max scaling? Provide an example to illustrate its application.

Unit Vector scalling is done considering the whole feature vector to be of unit length. This usually means dividing each component by the Euclidean length of the vector (L2 Norm)

In min max scalling we try to bring the feature in ceratain range 

In [10]:
df[['tip']].apply(lambda x: x/np.linalg.norm(x,1))

tip
0     0.000169
1     0.000000
2     0.000185
3     0.000483
4     0.000086
...        ...
6428  0.000083
6429  0.000000
6430  0.000000
6431  0.000000
6432  0.000264

[6433 rows x 1 columns]

# Q3. What is PCA (Principle Component Analysis), and how is it used in dimensionality reduction? Provide an example to illustrate its application.

PCA is used to reduce the dimension and try to keep the varaince in the data ,PCA generally tries to find the lower-dimensional surface to project the high-dimensional data.

In [11]:
from sklearn.decomposition import PCA

In [15]:
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
pca = PCA(n_components=2)
pca.fit(X)

PCA(n_components=2)

In [16]:
print(pca.explained_variance_ratio_)

[0.99244289 0.00755711]


In [19]:
pca = PCA(n_components=1)
pca.fit(X)
print(pca.explained_variance_ratio_)

[0.99244289]


# Q4. What is the relationship between PCA and Feature Extraction, and how can PCA be used for Feature Extraction? Provide an example to illustrate this concept.

PCA is a dimensionality reduction that identifies important relationships in our data, transforms the existing data based on these relationships, and then quantifies the importance of these relationships so we can keep the most important relationships and drop the others.

We identify the relationship among features through a Covariance Matrix.
Through the linear transformation or eigendecomposition of the Covariance Matrix, we get eigenvectors and eigenvalues.
Then we transform our data using Eigenvectors into principal components.
Lastly, we quantify the importance of these relationships using Eigenvalues and keep the important principal components.

# Q5. You are working on a project to build a recommendation system for a food delivery service. The dataset contains features such as price, rating, and delivery time. Explain how you would use Min-Max scaling to preprocess the data.

As the features are in different units we can use Min Max scaler to scale down the 
features in single range of 0,1 

In [23]:
d={'price':[200,300,340,560,900],
  'rating':[3,5,2,1,3],
  'time':[1,1.5,2,1,2]}

In [24]:
df=pd.DataFrame(d)

In [25]:
df.head()

price  rating  time
0    200       3   1.0
1    300       5   1.5
2    340       2   2.0
3    560       1   1.0
4    900       3   2.0

In [26]:
from sklearn.preprocessing import MinMaxScaler

In [27]:
min_max=MinMaxScaler()


In [28]:
min_max.fit_transform(df)

array([[0.        , 0.5       , 0.        ],
       [0.14285714, 1.        , 0.5       ],
       [0.2       , 0.25      , 1.        ],
       [0.51428571, 0.        , 0.        ],
       [1.        , 0.5       , 1.        ]])

# Q6. You are working on a project to build a model to predict stock prices. The dataset contains many features, such as company financial data and market trends. Explain how you would use PCA to reduce the dimensionality of the dataset.

We identify the relationship among features through a Covariance Matrix.
Through the linear transformation or eigendecomposition of the Covariance Matrix, we get eigenvectors and eigenvalues.
Then we transform our data using Eigenvectors into principal components.
Lastly, we quantify the importance of these relationships using Eigenvalues and keep the important principal components.

# Q7. For a dataset containing the following values: [1, 5, 10, 15, 20], perform Min-Max scaling to transform the values to a range of -1 to 1.

In [48]:
a=np.array([[1, 5, 10, 15, 20]])

In [49]:
a

array([[ 1,  5, 10, 15, 20]])

In [50]:
from sklearn.preprocessing import MinMaxScaler

In [51]:
min_max=MinMaxScaler()

In [72]:
var=min_max.fit_transform(a)

In [73]:
var

array([[0., 0., 0., 0., 0.]])

# Q8. For a dataset containing the following features: [height, weight, age, gender, blood pressure], perform Feature Extraction using PCA. How many principal components would you choose to retain, and why?

In [59]:
d={
    'height':[150,160,145,140,150],
    'weight':[60,55,60,67,56],
    'age':[30,23,32,35,56],
    'gender':[0,1,1,0,0],
    'blood pressure':[120,222,140,122,126]
}

In [60]:
df=pd.DataFrame(d)

In [61]:
df

height  weight  age  gender  blood pressure
0     150      60   30       0             120
1     160      55   23       1             222
2     145      60   32       1             140
3     140      67   35       0             122
4     150      56   56       0             126

In [62]:
from sklearn.decomposition import PCA

In [63]:
pca=PCA(n_components=3)

In [64]:
pca.fit(df)

PCA(n_components=3)

In [65]:
pca.components_

array([[ 0.13518378, -0.06060174, -0.16188524,  0.00919141,  0.97558263],
       [ 0.20237295, -0.26422182,  0.93639138, -0.00893338,  0.1110108 ],
       [ 0.78596167, -0.51113452, -0.29180319, -0.01219391, -0.1889655 ]])

In [66]:
pca.explained_variance_ratio_

array([0.93324651, 0.05513564, 0.01074739])

In [71]:
pca.singular_values_

array([88.50381122, 21.51196002,  9.49763213])